import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <h1>
          Hello World
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ut illum unde beatae, dignissimos blanditiis repudiandae cumque magni accusantium officia vero. Fuga, exercitationem voluptatum. Fugiat quisquam similique incidunt adipisci, ipsam deleniti!
        </p>
      </main>
    </>
  )
}
